### ISSUE TITLE
Postgres Issue: No tables found

### ISSUE THREAD

**Issue by mattsears** [kiwanami/emacs-edbi#16]
Hello, it seems that edbi can connect with my local Postgres database fine, but edbi says "No tables found" after connection. 

```
DB: dbi:Pg:dbname=test_app_dev

No tables.
```

However, there are several tables in the database it's connected to.  Here is the connection string I'm using. 

```
dbi:Pg:dbname=test_app_dev
```

I've verified the database exists with tables and I've connected to it with a short Perl script.

**Comment by stardiviner** [comment]
I got same error too, I use the latest git version edbi which installed from el-get.
And the buffer can't be closed wiith `[q]` if no tables.

**Comment by kiwanami** [comment]
Hi @stardiviner 
Thank you for your report. I'll check it.
Well, I'm busy with my work now. Please wait a while.

**Comment by stardiviner** [comment]
@kiwanami It's ok, check whenever you have time.
