### ISSUE TITLE
Can't install from melpa-stable

### ISSUE THREAD

**Issue by fvides** [kiwanami/emacs-edbi#38]
Hello

I'm interested in try this program, but can't install from repository melpa-stable, since it requires epc-0.1.1 and only the epc-0.1.0 is available.

Thanks!

**Comment by kiwanami** [comment]
Hi, @fvides 
I made the stable tag 0.1.1.
That may resolve the dependence on epc-0.1.1 from melpa-stable.
If you have a time, will you check it?

**Comment by fvides** [comment]
Hi, 

I've checked it and except for a minor error compiling edbi-demo.el everything aparently went fine. I'll use the system when I have the time and report if I find some other problem.

Many thanks!!

**Comment by kiwanami** [comment]
Thank you!
