### ISSUE TITLE
add two tips

### ISSUE THREAD

**Issue by ghost** [kiwanami/emacs-edbi#44]
1、connect to a database contains chinese
```
uri: dbi:mysql:dbname=db:mysql_enable_utf8=1
```
2、connect to a remote database with the ssh tunnel
first, open a tunnel
```
ssh -fNL 3306:localhost:3306 myname@myhost
```
then, connect to the local port like tip 1

**Comment by kiwanami** [comment]
Yeah. I usually use these tips.
Thanks for your sharing.
